import { IChatListProps } from "@/components/ChatList/type";

export const messageList = (): IChatListProps["messages"] => [
  {
    id: "1",
    senderId: "John Doe",
    text: "Hello! How are you?",
    timestamp: new Date().toISOString(),
    type: "text",
  },
  {
    id: "2",
    senderId: "Jane Smith",
    text: "I'm good, thanks! How about you?",
    type: "image",
    timestamp: new Date().toISOString(),
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you!",
    type: "video",
    timestamp: new Date().toISOString(),
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you!",
    type: "video",
    timestamp: new Date().toISOString(),
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you!",
    type: "video",
    timestamp: new Date().toISOString(),
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you!",
    type: "video",
    timestamp: new Date().toISOString(),
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you!",
    type: "video",
    timestamp: new Date().toISOString(),
  },
  {
    id: "1",
    senderId: "John Doe",
    text: "Hello! How are you?",
    timestamp: new Date().toISOString(),
    type: "text",
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you!",
    type: "video",
    timestamp: new Date().toISOString(),
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you!",
    type: "video",
    timestamp: new Date().toISOString(),
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you! ",
    type: "video",
    timestamp: new Date().toISOString(),
  },
  {
    id: "1",
    senderId: "John Doe",
    text: "Hello! How are you?",
    timestamp: new Date().toISOString(),
    type: "text",
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you!",
    type: "video",
    timestamp: new Date().toISOString(),
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you!",
    type: "video",
    timestamp: new Date().toISOString(),
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you!",
    type: "video",
    timestamp: new Date().toISOString(),
  },
  {
    id: "3",
    senderId: "John Doe",
    text: "I'm doing well, thank you!",
    type: "video",
    timestamp: new Date().toISOString(),
  },
];
